apiVersion: v1
kind: Secret
metadata:
  name: testapp-tls-secret
  namespace: default              #<-- create this secret in same namespace as ingress component
data:
  tls.crt: <base64 encoded file content for cert>
  tls.key: <base64 encoded file content for key>
type: kubernetes.io/tls