resource "local_file" "jas" {
  filename        = var.filename[0]
  content         = var.file-content["statement2"]
  file_permission = "0770"
  lifecycle {
    create_before_destroy = true
  }
}

resource "local_file" "jas1" {
  filename        = var.filename[1]
  content         = "\n \n Testing the invocation of output of other resource: ${random_pet.test.id} \n \n"
  file_permission = "0755"
  depends_on = [
    random_pet.test
  ]
}

resource "local_file" "jas2" {
  filename        = var.filename[2]
  content         = data.local_file.test1.content
  file_permission = "0755"
  depends_on = [
    random_pet.test
  ]
  #  lifecycle {
  #    prevent_destroy = true
  #  }
}

resource "random_pet" "test" {
  prefix    = var.prefix[0]
  separator = var.separator
  length    = var.length
  lifecycle {
    ignore_changes = [
      length
    ]
  }
}

output "test" {
  value       = random_pet.test.id
  description = "Records value of ID generated by random_pet resource"

}

data "local_file" "test1" {
  filename = var.filename[3]
}